# Homework Project: Crime Prediction
 #### Name : Rohan Satishrao Borde
 


# PART1: Decision Trees

In [1]:
import pandas as pd
import numpy as np
from sklearn import tree, metrics
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import LinearSVC
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
from sklearn.cross_validation import train_test_split
import matplotlib.pyplot as plt

C:\Users\borde\Anaconda3.4\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
#load clean data

df = pd.read_csv("Crime Prediction Data\\communities-crime-clean.csv")

1 a Create a new field “highCrime” which is true if the crime rate per capita (ViolentCrimesPerPop) is greater than 0.1, and false otherwise. 

In [3]:
highCrime = []
pos=0
neg=0

for i in df["ViolentCrimesPerPop"]:
    if i > 0.1:
        highCrime.append(True)
        pos+=1
    else:
        highCrime.append(False)
        neg+=1

highCrime = pd.DataFrame(highCrime)


Percentage of positive and negative instances in the dataset

In [4]:
#Positive Instances

print("Percentage of Positive Instances: ", pos/len(highCrime)*100)

Percentage of Positive Instances:  62.719518314099346


In [5]:
#Negative Instances

print("Percentage of Negative Instances: ", neg/len(highCrime)*100)

Percentage of Negative Instances:  37.280481685900654


1 b Use DecisionTreeClassifier to learn a decision tree to predict highCrime on the entire dataset 

In [6]:
# Remove non predictive attribute

df = df.drop(["state"], axis=1)
df = df.drop(["communityname"], axis=1)
df = df.drop(["fold"], axis=1)
df = df.drop(["ViolentCrimesPerPop"], axis=1)
df = pd.DataFrame(df)

In [7]:
# Build Decision Tree Classifier 

DT_clf = tree.DecisionTreeClassifier()
DT_clf = DT_clf.fit(df, highCrime)

In [8]:
# Predict class vale for df
DT_prediction = DT_clf.predict(df)

In [9]:
sum(DT_prediction != highCrime[0].values)

0

1 b i.What are the training accuracy, precision, and recall for this tree 

In [10]:
# Accuracy

metrics.accuracy_score(highCrime, DT_prediction)

1.0

In [11]:
# Precision

metrics.precision_score(highCrime, DT_prediction)

1.0

In [12]:
# Recall

metrics.recall_score(highCrime, DT_prediction)

1.0

1 b ii.	What are the main features used for classification? 

In [13]:
# Number of feature when fit is performed

DT_clf.n_features_

100

In [14]:
# The features importance

DT_clf.feature_importances_

array([ 0.00280397,  0.        ,  0.0055261 ,  0.08646058,  0.0014306 ,
        0.04798129,  0.00330825,  0.00597891,  0.00160942,  0.        ,
        0.00183934,  0.        ,  0.00107295,  0.        ,  0.00403666,
        0.00239519,  0.        ,  0.00601559,  0.        ,  0.        ,
        0.        ,  0.00286119,  0.01318694,  0.00632203,  0.01213059,
        0.00974181,  0.01134075,  0.        ,  0.00805505,  0.02584044,
        0.00449564,  0.00235628,  0.01128904,  0.01497339,  0.02220008,
        0.00046693,  0.00712654,  0.00340861,  0.        ,  0.00505792,
        0.00501368,  0.0107989 ,  0.00477324,  0.00199994,  0.36366775,
        0.00747369,  0.00785874,  0.00565052,  0.00322825,  0.00178825,
        0.00736016,  0.00690762,  0.01068921,  0.00496621,  0.00208458,
        0.01439976,  0.        ,  0.00769877,  0.        ,  0.00390569,
        0.01043216,  0.00868173,  0.01108986,  0.        ,  0.        ,
        0.        ,  0.00200072,  0.00355081,  0.00214098,  0.00

Above output reprsent the number of feature used for the Decision tree classification with their score. The higher, the more important the feature. The importance of a feature is computed as the (normalized) total reduction of the criterion brought by that feature.

In [15]:
# Importance Features

importantFeatures = sorted(zip(df.columns, DT_clf.feature_importances_), key=lambda x: x[1], reverse=True)
print(importantFeatures[:1])

[('PctKids2Par', 0.36366774504976823)]



1 c.Now apply cross-validation (cross_val_score) to do 10-fold cross-validation to estimate the out-of-training accuracy of decision tree learning for this task.

train and test data split


In [16]:
x_train, x_test, y_train, y_test = train_test_split(df,highCrime,test_size=0.1)

In [17]:
DT_clf1 = tree.DecisionTreeClassifier()
DT_clf1 = DT_clf1.fit(x_train, y_train)

In [18]:
y_pred = DT_clf1.predict(x_test)

In [19]:
# Accuracy

metrics.accuracy_score(y_test,y_pred)

0.79500000000000004

In [20]:
# Precision

metrics.precision_score(y_test,y_pred)

0.8214285714285714

In [21]:
# Recall

metrics.recall_score(y_test,y_pred)

0.87786259541984735

Cross Validation

1 c i.	What are the 10-fold cross-validation accuracy, precision, and recall?

In [22]:
# Accuracy
DT_clf2 = tree.DecisionTreeClassifier()
cross_val_score(DT_clf2,df,highCrime[0].values,cv=10, scoring='accuracy')

array([ 0.72      ,  0.825     ,  0.72      ,  0.75376884,  0.65829146,
        0.63819095,  0.73366834,  0.67336683,  0.77889447,  0.71859296])

In [23]:
# Precision

cross_val_score(DT_clf2,df,highCrime[0].values,cv=10, scoring='precision')

array([ 0.76258993,  0.82945736,  0.76691729,  0.77536232,  0.74545455,
        0.75      ,  0.77443609,  0.82      ,  0.78985507,  0.76271186])

In [24]:
# Recall

cross_val_score(DT_clf2,df,highCrime[0].values,cv=10, scoring='recall')

array([ 0.888,  0.848,  0.808,  0.864,  0.64 ,  0.664,  0.792,  0.616,
        0.88 ,  0.744])

# Linear Classification

2 a i.What is the 10-fold cross-validation accuracy, precision, and recall for this method?

In [25]:
x_train, x_test, y_train, y_test = train_test_split(df,highCrime,test_size=0.1)

In [26]:
GNB_clf1 = tree.DecisionTreeClassifier()
GNB_clf1 = GNB_clf1.fit(x_train, y_train)

In [27]:
y_pred = GNB_clf1.predict(x_test)

In [28]:
# Accuracy

metrics.accuracy_score(y_test,y_pred)

0.745

In [29]:
# Precission

metrics.precision_score(y_test,y_pred)

0.79389312977099236

In [30]:
# Recall

metrics.recall_score(y_test,y_pred)

0.8125

Cross Validation

In [31]:
# Accuracy
GNB_clf2 = GaussianNB()
cross_val_score(GNB_clf2,df,highCrime[0].values,cv=10, scoring='accuracy')

array([ 0.775     ,  0.8       ,  0.825     ,  0.79899497,  0.70351759,
        0.65326633,  0.81407035,  0.73366834,  0.71356784,  0.79899497])

In [32]:
# Precision

cross_val_score(GNB_clf2,df,highCrime[0].values,cv=10, scoring='precision')

array([ 0.86363636,  0.92929293,  0.95      ,  0.92079208,  0.94594595,
        0.86842105,  0.92307692,  1.        ,  0.77868852,  0.93814433])

In [33]:
# Recall

cross_val_score(GNB_clf2,df,highCrime[0].values,cv=10, scoring='recall')

array([ 0.76 ,  0.736,  0.76 ,  0.744,  0.56 ,  0.528,  0.768,  0.576,
        0.76 ,  0.728])

2 a ii.	What are the 10 most predictive features

In [34]:
# Funtion to measured normalized absolute difference of means for the feature between the two classes

def predictive_features(data,highCrime):
    true_data = []
    false_data = []
    res=[]
    for i in range(len(highCrime)):
        if (highCrime[0].values[i]):
            true_data.append(data[i])
        else:
            false_data.append(data[i])

    return abs(np.mean(true_data)-np.mean(false_data))/ (np.std(true_data)+np.std(false_data))

In [35]:
# Most Predictive Features

pf=[]
for i in df.columns:
    pf.append(predictive_features(df[i],highCrime))


importantPredictiveFeatures = sorted(zip(df.columns, pf), key=lambda x: x[1], reverse=True)

importantPredictiveFeatures[:10]

[('PctKids2Par', 0.80974842822770576),
 ('PctFam2Par', 0.74554480821667002),
 ('racePctWhite', 0.73522995312324224),
 ('PctIlleg', 0.70926105120057914),
 ('FemalePctDiv', 0.69397808830331542),
 ('TotalPctDiv', 0.67464460922247593),
 ('PctYoungKids2Par', 0.66500856988477031),
 ('pctWInvInc', 0.66107643266548766),
 ('PctTeen2Par', 0.64294944817476585),
 ('MalePctDivorce', 0.61686365922304187)]

2 b.	Use LinearSVC to learn a linear Support Vector Machine model to predict highCrime

In [36]:
x_train, x_test, y_train, y_test = train_test_split(df,highCrime,test_size=0.1)

In [37]:
LSVC_clf = LinearSVC()
LSVC_clf = LSVC_clf.fit(x_train, y_train)

C:\Users\borde\Anaconda3.4\lib\site-packages\sklearn\utils\validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [38]:
y_pred = LSVC_clf.predict(x_test)

In [39]:
# Accuracy

metrics.accuracy_score(y_test,y_pred)

0.82999999999999996

In [40]:
# Precision

metrics.precision_score(y_test,y_pred)

0.8584070796460177

In [41]:
# Recall

metrics.recall_score(y_test,y_pred)

0.84347826086956523

Cross Validation

In [42]:
# Accuracy
LSVC_clf1 = LinearSVC()
cross_val_score(LSVC_clf1,df,highCrime[0].values,cv=10, scoring='accuracy')

array([ 0.79      ,  0.865     ,  0.84      ,  0.80904523,  0.69346734,
        0.69346734,  0.81407035,  0.8241206 ,  0.81909548,  0.81407035])

In [43]:
# Precision

cross_val_score(LSVC_clf1,df,highCrime[0].values,cv=10, scoring='precision')

array([ 0.76774194,  0.84507042,  0.82517483,  0.85950413,  0.87209302,
        0.7962963 ,  0.84920635,  0.95918367,  0.80689655,  0.87288136])

In [44]:
# Recall

cross_val_score(LSVC_clf1,df,highCrime[0].values,cv=10, scoring='recall')

array([ 0.952,  0.96 ,  0.944,  0.832,  0.6  ,  0.688,  0.856,  0.752,
        0.936,  0.824])

2 b ii.	What are the 10 most predictive features? 

TODO

2 b iii.How do these results compare with your results from decision trees, above?
TODO

# Polynomial Features

3 c i. What is the estimated MSE of the model under 10-fold CV?

In [45]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import Pipeline
from sklearn import metrics
import matplotlib.pyplot as plt

polynomial_features = PolynomialFeatures(degree=2, include_bias=False)

linear_regression = LinearRegression()
model = Pipeline([("polynomial_features", polynomial_features),("linear_regression", linear_regression)])

model.fit(df,highCrime)

cross_val_score(model,df,highCrime[0].values, scoring='neg_mean_squared_error',cv=10)

# X_train, X_test, y_train, y_test = train_test_split(df, highCrime, test_size=0.1)
            
# model.fit(X_train, y_train)
            
# y_pred = model.predict(X_test)

# metrics.mean_squared_error(y_test, y_pred)

array([-0.92207528, -1.33625417, -1.43833719, -0.90041266, -0.79430701,
       -1.56120235, -0.75646181, -0.80265849, -1.53556356, -1.00686357])

3 b ii.	What is the MSE on the training set (train on all the data then test on it all)?

In [46]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import Pipeline
from sklearn import metrics

polynomial_features = PolynomialFeatures(degree=2, include_bias=False)

linear_regression = LinearRegression()
model = Pipeline([("polynomial_features", polynomial_features),("linear_regression", linear_regression)])
            
model.fit(df, highCrime)
            
y_pred = model.predict(df)

metrics.mean_squared_error(highCrime, y_pred)

4.8628578204929309e-28

# Dirty Data

In [47]:
#load un-clean data

df = pd.read_csv("Crime Prediction Data\\communities-crime-full.csv")

In [48]:
# Data Cleaning
df = pd.DataFrame(df)
df = df.replace(['?'], [np.nan]) 
# df = df.groupby(df.columns, axis = 1).transform(lambda x: x.fillna(x.mean()))
# df.where(pd.notnull(df), df.mean(), axis='columns')
# df.apply(lambda x: x.fillna(x.mean()),axis=0)

# imp = Imputer(missing_values=np.nan,strategy=‘mean’, axis=0)
# imp.fit([1, 2, 3, 4, 5, 6, 7])
# df = pd.Series(imp.transform(df).tolist()[0])

df = df.fillna((df.mean()))
# df = df.dropna()
print(df.LemasSwornFT)

0       0.03
1        NaN
2        NaN
3        NaN
4        NaN
5        NaN
6        NaN
7        NaN
8        NaN
9        NaN
10       NaN
11       NaN
12       NaN
13       NaN
14       NaN
15       NaN
16      0.06
17       NaN
18       NaN
19       NaN
20      0.03
21      0.25
22       NaN
23      0.01
24       NaN
25       NaN
26       NaN
27       NaN
28       NaN
29       NaN
        ... 
1964     NaN
1965    0.21
1966     NaN
1967     NaN
1968     NaN
1969    0.39
1970     NaN
1971     NaN
1972     NaN
1973     NaN
1974     NaN
1975     NaN
1976     NaN
1977     NaN
1978     NaN
1979     NaN
1980     NaN
1981    0.01
1982     NaN
1983     NaN
1984     NaN
1985     NaN
1986     NaN
1987     NaN
1988     NaN
1989     NaN
1990     NaN
1991    0.06
1992    0.02
1993    0.03
Name: LemasSwornFT, dtype: object


In [49]:
highCrime = []
pos=0
neg=0

for i in df["ViolentCrimesPerPop"]:
    if i > 0.1:
        highCrime.append(True)
        pos+=1
    else:
        highCrime.append(False)
        neg+=1

highCrime = pd.DataFrame(highCrime)

In [50]:
# Drop Non Predictive Column

df = df.drop(['state','county','community','communityname','fold'], axis=1)

In [51]:
#Positive Instances

print("Percentage of Positive Instances: ", pos/len(highCrime)*100)

Percentage of Positive Instances:  62.7382146439318


In [52]:
#Negative Instances

print("Percentage of Negative Instances: ", neg/len(highCrime)*100)

Percentage of Negative Instances:  37.2617853560682


Train and Test Data Split

In [53]:
# Accuracy

DT_clf3 = tree.DecisionTreeClassifier()
cross_val_score(DT_clf3,df,highCrime[0].values,cv=10, scoring='accuracy')

ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

In [ ]:
# Precision

DT_clf3 = tree.DecisionTreeClassifier()
cross_val_score(DT_clf3,df,highCrime[0].values,cv=10, scoring='precision')

In [ ]:
# Recall

DT_clf3 = tree.DecisionTreeClassifier()
cross_val_score(DT_clf3,df,highCrime[0].values,cv=10, scoring='recall')

ii.	Devise a method to find the most useful threshold for dividing high crime areas from low crime areas (i.e., discretizing XXX to compute highCrime). Define clearly what you mean by “useful”.

In [ ]:
from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt
import random

lc = LinearRegression()
lc = lc.fit(df,highCrime)
y_pred = lc.predict(df)

false_positive_rate, true_positive_rate, thresholds = roc_curve(highCrime[0].values, y_pred)
roc_auc = auc(false_positive_rate, true_positive_rate)

plt.title('Receiver Operating Characteristic')
plt.plot(false_positive_rate, true_positive_rate, 'b',
label='AUC = %0.2f'% roc_auc)
plt.legend(loc='lower right')
plt.plot([0,1],[0,1],'r--')
plt.xlim([-0.1,1.2])
plt.ylim([-0.1,1.2])
plt.ylabel('True Positive Rate')
plt.xlabel('False Positive Rate')
plt.show()

# Extra Credit


5 a i.Experiment with two learning methods other than those described above (one can be a non-linear kernel for SVM) for the classification problem, explaining clearly what you did. Show CV results for both the clean and full datasets.

C-Support Vector Classification for clean data

In [ ]:
# Cross Validation for clean data

from sklearn import svm

df = pd.read_csv("Crime Prediction Data\\communities-crime-clean.csv")

highCrime = []
for i in df["ViolentCrimesPerPop"]:
    if i > 0.1:
        highCrime.append(True)
    else:
        highCrime.append(False)
highCrime = pd.DataFrame(highCrime)

# Drop Non Predictive Column

df = df.drop(['state','communityname','fold'], axis=1)
df = pd.DataFrame(df)

SVM = svm.SVC(kernel='linear')
# SVM = SVM.fit(df,highCrime)
Accuracy = cross_val_score(SVM,df,highCrime[0].values,cv=10, scoring='accuracy')
Recall = cross_val_score(SVM,df,highCrime[0].values,cv=10, scoring='recall')
Precision = cross_val_score(SVM,df,highCrime[0].values,cv=10, scoring='precision')

print("Accuracy\n",Accuracy)
print("Recall\n",Recall)
print("Precision\n",Precision)

C-Support Vector Classification for full data

In [ ]:
# Cross validation for Un-clean data
from sklearn import svm
#load un-clean data

df1 = pd.read_csv("Crime Prediction Data\\communities-crime-full.csv")

# Data Cleaning

df1 = df1.replace('?', np.nan) 
df1 = df1.dropna()

highCrime = []

for i in df1["ViolentCrimesPerPop"]:
    if i > 0.1:
        highCrime.append(True)
    else:
        highCrime.append(False)

highCrime = pd.DataFrame(highCrime)

# Drop Non Predictive Column

df1 = df1.drop(['state','county','community','communityname','fold'], axis=1)

df1 = pd.DataFrame(df1)

SVM = svm.SVC(kernel='linear')
# SVM = SVM.fit(df,highCrime)
accuracy = cross_val_score(SVM,df1,highCrime[0].values,cv=10, scoring='accuracy')
print("Accuracy\n", accuracy)
recall = cross_val_score(SVM,df1,highCrime[0].values,cv=10, scoring='recall')
print("Recall\n", recall)
precision =  cross_val_score(SVM,df1,highCrime[0].values,cv=10, scoring='precision')
print("Precision", precision)

Nu-Support Vector Classification clean data

In [ ]:
# Cross Validation for clean data

from sklearn import svm

df = pd.read_csv("Crime Prediction Data\\communities-crime-clean.csv")

highCrime = []
for i in df["ViolentCrimesPerPop"]:
    if i > 0.1:
        highCrime.append(True)
    else:
        highCrime.append(False)
highCrime = pd.DataFrame(highCrime)

# Drop Non Predictive Column

df = df.drop(['state','communityname','fold'], axis=1)
df = pd.DataFrame(df)

NUSVM = svm.NuSVC(kernel='linear')
# NUSVM = NUSVM.fit(df,highCrime)
accuracy = cross_val_score(NUSVM,df,highCrime[0].values,cv=10, scoring='accuracy')
print("Accuracy\n", accuracy)
recall = cross_val_score(NUSVM,df,highCrime[0].values,cv=10, scoring='recall')
print("Recall\n", recall)
precision =  cross_val_score(NUSVM,df,highCrime[0].values,cv=10, scoring='precision')
print("Precision\n", precision)

Nu-Support Vector Classification full data

In [ ]:
# Cross validation for Un-clean data
from sklearn import svm
#load un-clean data

df1 = pd.read_csv("Crime Prediction Data\\communities-crime-full.csv")

# Data Cleaning

df1 = df1.replace('?', np.nan) 
df1 = df1.dropna()

highCrime = []

for i in df1["ViolentCrimesPerPop"]:
    if i > 0.1:
        highCrime.append(True)
    else:
        highCrime.append(False)

highCrime = pd.DataFrame(highCrime)

# Drop Non Predictive Column

df1 = df1.drop(['state','county','community','communityname','fold'], axis=1)

df1 = pd.DataFrame(df1)

NUSVM = svm.NuSVC(kernel='linear')
# NUSVM = NUSVM.fit(df,highCrime)
accuracy = cross_val_score(NUSVM,df1,highCrime[0].values,cv=10, scoring='accuracy')
print("Accuracy\n", accuracy)
recall = cross_val_score(NUSVM,df1,highCrime[0].values,cv=10, scoring='recall')
print("Recall\n", recall)
precision =  cross_val_score(NUSVM,df1,highCrime[0].values,cv=10, scoring='precision')
print("Precision\n", precision)